### ISSUE TITLE
Unknown sequence name in BAM

### ISSUE THREAD

**Issue by tly0505** [guertinlab/seqOutBias#2]
Hi,
I've been having trouble with using 'table' and 'scale' commands.
 When running 
`seqOutBias table genomefile.tbl myfile.sorted.bam` 
 I get:
`# tabulate myfile.sorted.bam
Error: Unknown sequence name in BAM: chr2`

Do you know what might be wrong? Thanks for your help!

**Comment by andrelmartins** [comment]
Hi,

That particular error occurs because the BAM file contains a sequence name "chr2" that was not present in the FASTA file used to build "genomefile.tbl". Sometimes different sources for the same genome assembly use a different convention for sequence names, like using '2' instead of 'chr2'.

If the FASTA file does indeed use "2" instead of "chr2", you can try something like:
`sed -e 's/^>/>chr/g' genome.fa > genome_chr.fa`
and use the resulting file to build the "genomefile.tbl" file.

Hope this helps!

**Comment by tly0505** [comment]
Thanks for such quick reply!

Hmm, my genome FASTA file does have notations in the form chrN 

` cat genomefile.fa | grep chr2 -n`

25808356:>chr20
27068868:>chr21
28031467:>chr21_gl000210_random
28032022:>chr22
29058115:>chr2

Before I have tried changing the sequence names from "chrN" to "N" in the BAM file header as well...

It doesn't appear to have an issue with chr1 which comes before chr2 in the BAM/SAM header.

I shall try remaking the .tbl file in case it is incomplete or something and get back to you.

**Comment by tly0505** [comment]
Ok, I've redone the .tbl file and it works fine, sorry for the confusion!

Thanks for your help!
